version: '3'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.15.0
    container_name: artifactory
    ports:
     - 8081:8081
    volumes:
     - /home/frank/development/projects/takeda/data/artifactory:/var/opt/jfrog/artifactory
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

  bitbucket:
     image: atlassian/bitbucket-server
     container_name: bitbucket
     ports: 
      - 7990:7990
      - 7999:7999
     volumes:
      - /home/frank/development/projects/takeda/data/bitbucket:/var/atlassian/application-data/bitbucket

  jenkins:
     image: jenkinsci/blueocean
     ports:
      - 8080:8080
      - 50000:50000
     volumes:
      - /home/frank/development/projects/takeda/data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock 
     privileged: true 
