= Local Jenkins, Artifactory, Bitbucket

//depracated

== Install

. Install docker-compose

    sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
+
or

    apt install docker-compose

. Create a folder to persist data
+
I used `/home/frank/development/projects/takeda/data`. don't forget to change the values in the `docker-compose.yml` file to reflect this.

    mkdir -p /data/{jenkins,artifactory,bitbucket,sonar}
    chmod -R 777 /data
+
You need to change mod, otherwise, the apps will have permission problems.

. Copy 'docker-compose.yml` file into `/data`

. Start docker compose

    docker-compose up

. Initial startup

.. Jenkins

For jenkins you will have to search in the logs for the initial password

jenkins_1 | Jenkins initial setup is required.
An admin user has been created and a password generated.
jenkins_1 | Please use the following password to proceed to installation:
jenkins_1 | jenkins_1 | d1b5c23620874ca3b07daf63ab3111f1 jenkins_1 |
jenkins_1      | This may also be found at: /var/jenkins_home/secrets/initialAdminPassword

and once you get it, the app will be available at http://127.0.0.1:8080

.. Artifactory

artifactory you will have it available running at http://127.0.0.1
user: admin ,
password: password

.. BitBucket

or bitbucket, you will have to open a brower and points to  http://127.0.1:7990

Then you will be asked for a license, and you have 2 options

  c1) click on "I have an account" and use your google account or
  c2) click on "Create an account" and create you own account for receiving Evaluation licenses

Once you write down the license, you can continue with the installation and once it is installed you can play with the Bitbucket

 (you will be asked for setting a username & password)

